REM Run FridgeIQ for all puzzles. Roughly in order of complexity
python .\FridgeIQ --puzzle-name square_01
python .\FridgeIQ --puzzle-name rectangle_01
python .\FridgeIQ --puzzle-name triangle_01
python .\FridgeIQ --puzzle-name square_02
python .\FridgeIQ --puzzle-name triangle_02
python .\FridgeIQ --puzzle-name triangle_03
python .\FridgeIQ --puzzle-name square_03
python .\FridgeIQ --puzzle-name square_04
python .\FridgeIQ --puzzle-name rectangle_02_a
python .\FridgeIQ --puzzle-name rectangle_03
python .\FridgeIQ --puzzle-name triangle_04
python .\FridgeIQ --puzzle-name triangle_05
python .\FridgeIQ --puzzle-name rectangle_04_a
python .\FridgeIQ --puzzle-name rectangle_04_b
python .\FridgeIQ --puzzle-name square_05
python .\FridgeIQ --puzzle-name rectangle_05_a
python .\FridgeIQ --puzzle-name rectangle_05_b
python .\FridgeIQ --puzzle-name triangle_06
python .\FridgeIQ --puzzle-name square_06
python .\FridgeIQ --puzzle-name rectangle_06_a
python .\FridgeIQ --puzzle-name rectangle_06_b
python .\FridgeIQ --puzzle-name triangle_07
python .\FridgeIQ --puzzle-name square_07
python .\FridgeIQ --puzzle-name rectangle_07_a
python .\FridgeIQ --puzzle-name rectangle_07_b
python .\FridgeIQ --puzzle-name rectangle_07_c
python .\FridgeIQ --puzzle-name triangle_08
python .\FridgeIQ --puzzle-name square_08
python .\FridgeIQ --puzzle-name rectangle_08_a
python .\FridgeIQ --puzzle-name rectangle_08_b
python .\FridgeIQ --puzzle-name rectangle_08_c
python .\FridgeIQ --puzzle-name triangle_09
python .\FridgeIQ --puzzle-name square_09
python .\FridgeIQ --puzzle-name rectangle_09_a
python .\FridgeIQ --puzzle-name rectangle_09_b
python .\FridgeIQ --puzzle-name triangle_10
python .\FridgeIQ --puzzle-name square_10
python .\FridgeIQ --puzzle-name rectangle_10_a
python .\FridgeIQ --puzzle-name rectangle_10_b
python .\FridgeIQ --puzzle-name rectangle_10_c
python .\FridgeIQ --puzzle-name rectangle_10_d

python .\FridgeIQ --puzzle-name challenge_01
python .\FridgeIQ --puzzle-name challenge_02
python .\FridgeIQ --puzzle-name challenge_03
python .\FridgeIQ --puzzle-name challenge_04
python .\FridgeIQ --puzzle-name challenge_05
python .\FridgeIQ --puzzle-name challenge_06
